### ISSUE TITLE
xcode 6.1.1 好像没效果

### ISSUE THREAD

**Issue by Whirlwind** [dhcdht/DXXcodeConsoleUnicodePlugin#1]
log: 

```
2015-01-08 13:12:09.763 GD189[4579:190436] {
    cost = 0;
    date = "2014-12-30";
    duration = "00:03:11";
    id = 177;
    isDial = "\U4e3b\U53eb";
    locale = "\U676d\U5dde";
    "target_phone" = 10000;
    time = "20:02:36";
    type = "\U6f2b\U6e38";
}
```

**Comment by dhcdht** [comment]
我用的也是 Xcode6.1.1 现在，option+c 这个快捷键的方式是可以的。
如果要在 console 里边直接显示结果，需要在 Xcode 的菜单，edit 里边勾选上 ConvertUnicodeInConsole(Beta) 那个，如果不行的话请告诉我，我再看看。
抱歉，一直是自用，也没写使用方法出来

**Comment by Whirlwind** [comment]
option+c 是对剪贴板的内容进行显示？好像是可以。
直接显示结果好像失败了，我勾选了那个 beta，还是没出中文。

**Comment by dhcdht** [comment]
恩，是现实剪贴板里边的。
那个在 console 里边显示的我看看，它是检测 console 里边被写入了的东西，如果在开之前就在 console 里边，是不会显示出来的

**Comment by Whirlwind** [comment]
奇怪，我xcode有两个 window， 一个写代码，一个看 log。代码的 window 里面出现了前面是\u，后面是中文又打了一遍（好像没有全部），log 的 window 全是\u。程序全新启动，所以不存在 console 已经有数据。

**Comment by dhcdht** [comment]
前边是 \u，后边是中文是故意的，以前试过吧 \u 那个完全隐藏掉，但是怕中文打不出来的话就会看不见了，后来就这样不隐藏前边的，而是在后边打。
关于两个窗口这个……没考虑到这个情况，代码里只选了第一个找到窗口就打印了

**Comment by Whirlwind** [comment]
而且那个中文，是在所有 log 最后追加上的，也就是说，顺序不对。

**Comment by dhcdht** [comment]
额……确实是的，有时间我会再想想办法弄弄看

**Comment by dhcdht** [comment]
@Whirlwind 哈喽，在 console 中原处替换文本应该可以了。
同时开多个窗口的情况我还不太确定行不行，你可以用最新的代码再试试。

**Comment by Whirlwind** [comment]
好像都可以了！多窗口也可以。Good！但是，当 console 已经有内容，这时候再新开一个 window，新的 window 上面的 log 还是\u.不知道这个能处理吗？

**Comment by dhcdht** [comment]
这个……还挺高级的操作，我试了是不行……有时间我会再看看这个

**Comment by Whirlwind** [comment]
+1

**Comment by dhcdht** [comment]
@Whirlwind 新开 window，我试起来是可以的了
