### ISSUE TITLE
转化过长字条串时，弹出的窗体太长

### ISSUE THREAD

**Issue by bingxue314159** [dhcdht/DXXcodeConsoleUnicodePlugin#13]
非常感谢，这个插件太有用了！但在使用过程中，碰到了一个问题：
转化过长字条串时，弹出的窗体太长，超出了屏幕的范围，最好能适应当前屏幕大小，文字在内部滚动！
（ps,文字太长，同一段文字，有时会提示太长有时直接弹出窗体，这应该也是一个BUG了）

**Comment by dhcdht** [comment]
我弄了个滚动的 textView 装那些字
