### ISSUE TITLE
xcode6.4

### ISSUE THREAD

**Issue by codwam** [dhcdht/DXXcodeConsoleUnicodePlugin#3]
xcode6.4不可以，我试了在alcatraz上安装不成功

**Comment by akring** [comment]
同上，下载zip自行build也无法生效

**Comment by dhcdht** [comment]
@culmek @akring 添加了 Xcode 6.4 的UUID，现在应该可以在6.4上使用了。
每次升级都build很不方便，用 https://gist.github.com/dhcdht/7bd794314972855dc4b5 可以一次性升级那些插件，基本都能用

**Comment by codwam** [comment]
嗯，确实是。不过不知道为什么在alcatraz上安装不了。

**Comment by dhcdht** [comment]
嗯，我看见它给了
Wasn't able to find: DXXcodeConsoleUnicodePlugin.xcodeproj in /Users/dhc/Library/Application Support/Alcatraz/Plug-ins/DXXcodeConsoleUnicodePlugin
看起来是工程文件的名字不对应

**Comment by dhcdht** [comment]
给跪了，alcatraz那边代码就是只找文件名和显示名字一样的工程文件。
我这边改了项目名字，现在alcatraz可以用了

**Comment by codwam** [comment]
嗯，谢谢了
