### ISSUE TITLE
\U7684中文“的”没转换

### ISSUE THREAD

**Issue by codwam** [dhcdht/DXXcodeConsoleUnicodePlugin#4]

**Comment by dhcdht** [comment]
![image](https://cloud.githubusercontent.com/assets/1644510/8611866/36319988-26fa-11e5-9df9-2105be0d7a39.png)
我这边试起来两种方式这个都是可以的，应该和上下文有关，方便贴出来比较完整的整句话么？

**Comment by codwam** [comment]
有个页面，需要请求两个接口，但目前两个接口的数据是一样的：
title = "\U3010\U6ce8\U610f\U3011\U4ed6\U4eec\U4e70\U623f\U65f6\U88ab\U9a97\U4e86\Uff01\U4e8c\U624b\U623f\U7684\U732b\U817b\Uff0c\U4f60\U4e0d\U5f97\U4e0d\U77e5\Uff01";
title = "【注意】他们买房时被骗了！二手房的猫腻，你不得不知！";// 第一次是转换是可以的
title = "【注意】他们买房时被骗了！二手房\U7684猫腻，你不得不知！";// 第二次就这样了

title = "\U674e\U5f00\U590d\Uff1a\U5386\U7ecf\U6b7b\U4ea1\U540e\U6211\U4fee\U7684\U4e03\U4e2a\U5b66\U5206";
title = "李开复：历经死亡后我修的\U4e03个学分";// 两次都这样

**Comment by dhcdht** [comment]
![image](https://cloud.githubusercontent.com/assets/1644510/8612861/42db6000-270a-11e5-9345-e7a4ebaa53d1.png)
我试了多次都没有能复现问题，用的是 xcode 6.4。
出现的次数多么？
对于不行的那些字符，用 option+c 的快捷键翻译看一下吧先。抱歉了

**Comment by codwam** [comment]
好吧
