### ISSUE TITLE
求更新姿瓷Xcode 7 GM版本

### ISSUE THREAD

**Issue by akring** [dhcdht/DXXcodeConsoleUnicodePlugin#5]
GM版本失效了。。。

**Comment by dhcdht** [comment]
fa1a2b5b359d1e8a19dc4c61990a8b345f867e32
加入了 Xcode 7 GM 的支持。

我平时每次升级一般用这个把所有插件都加入新的UUID，一般都会还能使用
https://gist.github.com/dhcdht/7bd794314972855dc4b5

**Comment by akring** [comment]
OK
